language: java

jdk: openjdk10

cache:
  directories:
    - $HOME/.m2

jobs:
  include:
    - stage: unit tests
      script:
        - mvn clean test -DskipITs
        - mvn org.jacoco:jacoco-maven-plugin:report-aggregate
      after_success:
        - bash <(curl -s https://codecov.io/bash) -F unittests
    - stage: component tests
      script:
        - mvn clean integration-test verify -DskipUTs
