eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
    registerWithEureka: true
    fetchRegistry: true

spring:
  # ===============================
  # = Hibernate datasource
  # ===============================
  datasource:
    url: jdbc:mysql://127.0.0.1:3302/order_database
    username: order_database
    password: order_database

  # ===============================
  # = JPA configurations
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: MYSQL
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

management:
  endpoints:
    web:
      exposure:
        include: "*"

hystrix:
  command:
    findCustomerByAddress:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 8000
  threadpool:
    findCustomerByAddressPool:
      coreSize: 20
      allowMaximumSizeToDivergeFromCoreSize: true
      maximumSize: 100
