eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
    registerWithEureka: true
    fetchRegistry: true

#
#debug: true
#trace: true
#logging:
#  level:
#    org:
#      springframework:
#        cloud:
#          netflix: trace

management:
  endpoints:
    web:
      exposure:
        include: "*"

zuul:
  semaphore:
    max-semaphores: 350
  prefix: /api
  routes:
    account:
      path: /customer/**
      serviceId: customer-service
    order:
      path: /order/**
      serviceId: order-service
  #  ribbon-isolation-strategy: semaphore
  ribbon-isolation-strategy: THREAD
  threadPool:
    useSeparateThreadPools: true

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000

hystrix:
  threadpool:
    customer-service:
      coreSize: 10
      allowMaximumSizeToDivergeFromCoreSize: true
      maximumSize: 40


hystrix.command.default.circuitBreaker.enabled: false
ribbon:
  ReadTimeout: 4000
  SocketTimeout: 4000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0

  # performance with this settings: 10 req/sec
  #  MaxTotalConnections: 20
  #  MaxConnectionsPerHost: 10


  # performance with this settings: 20 req/sec
  #  MaxTotalConnections: 200
  #  MaxConnectionsPerHost: 20

  # performance with this settings: 120 req/sec
  MaxTotalConnections: 2000
  MaxConnectionsPerHost: 200
