version: '2.3'

services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.3.8
    environment:
      MYSQL_ROOT_PASSWORD: db_service
      MYSQL_DATABASE: db_service
      MYSQL_USER: db_service
      MYSQL_PASSWORD: db_service
    volumes:
    - ${PWD}/mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always