version: '2.3'

services:

  customer_database:
    container_name: customer_database
    image: mariadb:10.3.8
    environment:
      MYSQL_ROOT_PASSWORD: customer_database
      MYSQL_DATABASE: customer_database
      MYSQL_USER: customer_database
      MYSQL_PASSWORD: customer_database
    volumes:
      - ${PWD}/customer_database:/var/lib/mysql
    ports:
      - 3301:3306
    restart: always

  order_database:
    container_name: order_database
    image: mariadb:10.3.8
    environment:
      MYSQL_ROOT_PASSWORD: order_database
      MYSQL_DATABASE: order_database
      MYSQL_USER: order_database
      MYSQL_PASSWORD: order_database
    volumes:
      - ${PWD}/order_database:/var/lib/mysql
    ports:
      - 3302:3306
    restart: always
